import type { KPIData, TimeSeriesValue } from './types';

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const generateMonthlyData = (baseValue: number, variance: number = 0.05): TimeSeriesValue[] => {
    return months.map(month => ({
        month,
        actual: baseValue * (1 + (Math.random() * variance * 2 - variance)),
    }));
};

export const initialKPIs: Record<string, KPIData> = {
    'closing_cash': {
        id: 'closing_cash',
        label: 'Closing Cash Balance',
        data: months.map(m => ({ month: m, actual: 262672 })),
        unit: '$',
        formula: 'SUM',
        children: ['opening_cash', 'net_cash_flow'],
        isExpanded: true,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#10B981',
        desiredTrend: 'INCREASE',
    },
    'opening_cash': {
        id: 'opening_cash',
        label: 'Opening Cash Balance',
        data: generateMonthlyData(229861, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'closing_cash',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#9CA3AF',
        desiredTrend: 'INCREASE',
    },
    'net_cash_flow': {
        id: 'net_cash_flow',
        label: 'Net Cash Flow',
        data: months.map(m => ({ month: m, actual: 32811 })),
        unit: '$',
        formula: 'SUM',
        children: ['cf_ops', 'cf_inv', 'cf_fin'],
        parentId: 'closing_cash',
        isExpanded: true,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#10B981',
        desiredTrend: 'INCREASE',
    },
    'cf_ops': {
        id: 'cf_ops',
        label: 'Cash flow from operations',
        data: months.map(m => ({ month: m, actual: 49956 })),
        unit: '$',
        formula: 'SUM',
        children: ['cash_in', 'cash_out'],
        parentId: 'net_cash_flow',
        isExpanded: true,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#10B981',
        desiredTrend: 'INCREASE',
    },
    'cf_inv': {
        id: 'cf_inv',
        label: 'Cash flow from investing',
        data: generateMonthlyData(-9445, 0.1),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'net_cash_flow',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#EF4444',
        desiredTrend: 'INCREASE',
    },
    'cf_fin': {
        id: 'cf_fin',
        label: 'Cash flow from financing',
        data: generateMonthlyData(-7700, 0.1),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'net_cash_flow',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#EF4444',
        desiredTrend: 'INCREASE',
    },
    'cash_in': {
        id: 'cash_in',
        label: 'Cash In',
        data: months.map(m => ({ month: m, actual: 173955 })),
        unit: '$',
        formula: 'SUM',
        children: ['receipts'],
        parentId: 'cf_ops',
        isExpanded: true,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#10B981',
        desiredTrend: 'INCREASE',
    },
    'cash_out': {
        id: 'cash_out',
        label: 'Cash Out',
        data: months.map(m => ({ month: m, actual: -123998 })),
        unit: '$',
        formula: 'SUM',
        // Inverting signs in calculation isn't natively supported unless we do CUSTOM, 
        // to keep it simple, Cash Out constituents should negative.
        children: ['raw_materials', 'gen_admin', 'salaries', 'interest', 'tax'],
        parentId: 'cf_ops',
        isExpanded: true,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#EF4444',
        desiredTrend: 'DECREASE',
    },
    'receipts': {
        id: 'receipts',
        label: 'Cash Receipts From Customers',
        data: generateMonthlyData(173955, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_in',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#3B82F6',
        desiredTrend: 'INCREASE',
    },
    'raw_materials': {
        id: 'raw_materials',
        label: 'Raw Material Purchases',
        data: generateMonthlyData(-60227, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_out',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#F59E0B',
        desiredTrend: 'DECREASE',
    },
    'gen_admin': {
        id: 'gen_admin',
        label: 'General & Administrative',
        data: generateMonthlyData(-25551, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_out',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#F59E0B',
        desiredTrend: 'DECREASE',
    },
    'salaries': {
        id: 'salaries',
        label: 'Salaries & Wages',
        data: generateMonthlyData(-28060, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_out',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#F59E0B',
        desiredTrend: 'DECREASE',
    },
    'interest': {
        id: 'interest',
        label: 'Interest Expense',
        data: generateMonthlyData(-2678, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_out',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#F59E0B',
        desiredTrend: 'DECREASE',
    },
    'tax': {
        id: 'tax',
        label: 'Income Tax',
        data: generateMonthlyData(-7483, 0.05),
        unit: '$',
        formula: 'NONE',
        children: [],
        parentId: 'cash_out',
        isExpanded: false,
        simulationValue: 0,
        simulationType: 'PERCENT',
        color: '#F59E0B',
        desiredTrend: 'DECREASE',
    }
};
